python_web/python_web/urls.py
from django.contrib import admin
from django.urls import path, include

from login_demo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login),
    path('index/', views.index),    
    path('register/', views.register),
    path('logout/', views.logout),
    #python开源验证码包
    #path('captcha/', include('captcha.urls'))
]

python_web/login_demo/models.py
from django.db import models

class Users(models.Model):
    
    username = models.CharField(max_length = 666)
    password = models.CharField(max_length= 666)
    mobile = models.CharField(max_length = 666)
    gender = models.CharField(max_length = 8)
    registerTime = models.DateTimeField(auto_now_add = True)

python_web/login_demo/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from . import models


def index(request):
    #local()是Python中的一个内置函数，它可以将函数中的局部变量以字典的形式返回。
    #生产环境中，需要显示指定哪些变量值返回，否则可能会造成数据泄露  
    return render(request, 'index.html', locals())

def login(request):
    #如果用户已经登录，则直接跳转
    if request.session.get('isLogin', None):
        return redirect('/index/')
    if request.method == 'POST':
        username = request.POST.get('username')
        #生产环境中密码需要加密，为了主线简介，本例子暂不演示
        password = request.POST.get('password')
                
        #如果用户名和密码不为空，真实场景可以增加更多格式验证。
        message = '用户或密码错误，请输入正确的信息！'
        if username.strip() and password:
            try:
                #通过models查询数据库，免写sql语句，使用对象访问即可
                user = models.Users.objects.get(username=username)
                if user.password == password:
                    #登录成功后在session字典内写入用户状态；session里面写任何数据，不仅仅限于用户相关！
                    request.session['isLogin'] = True
                    return redirect('/index/')
                else:
                    return render(request, 'login.html', {'message': message})
            except:                
                return render(request, 'login.html', {'message': message})
        else:
            return render(request, 'login.html', {'message': message})
    return render(request,'login.html')

def register(request):
    #如果用户已经登录，则直接跳转
    if request.session.get('isLogin', None):
        return redirect('/index/')
    
    message = '请检查输入数据，是否合适！'
    if request.method == 'POST':
        username = request.POST.get('username')
        #生产环境中密码需要加密，为了主线简介，本例子暂不演示
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        #生产环境中数据需要判断格式，一般使用正则表达式完成，本例子暂不赘述
        gender = request.POST.get('gender')
        mobile = request.POST.get('mobile')
        user = ''
        if username.strip() and password1 and (password1 == password2):
            try:
                #通过models查询数据库，免写sql语句，使用对象访问即可
                user = models.Users.objects.get(username=username)
            except:                
                pass
            
            if user:
                message = '用户名已存在，请重新输入'
                return render(request, 'register.html', {'message': message})
            else:
                #通过models模版将数据写入数据库，可以避免sql，直接用对象做操作
                newUser = models.Users()
                newUser.username = username
                newUser.password = password1
                newUser.gender = gender
                newUser.mobile = mobile
                newUser.save()
                #注册成功后，转入登录界面
                return redirect('/')
        else:
            return render(request, 'register.html', {'message': message})
    #local()是Python中的一个内置函数，它可以将函数中的局部变量以字典的形式返回。
    #生产环境中，需要显示指定哪些变量值返回，否则可能会造成数据泄露  
    return render(request, 'register.html', locals())
    

def logout(request):
    print(index, 'logout--------------------')
    #如果用户已登录，则清空session，否则直接跳转
    if request.session.get('isLogin', True):
        request.session.flush()
    return redirect('/')

    # username = models.CharField(max_length = 666)
    # password = models.CharField(max_length= 666)
    # mobile = models.CharField(max_length = 666)
    # gender = models.CharField(max_length = 8)
    # registerTime = models.DateTimeField(auto_now_add = True)

python_web/login_demo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--title标签定义标题-->
    <title>您已成功登录</title>
</head>
<body>
    <!--div标识图层，将登录块隔离出来，方面集中控制格式，CSS margin(外边距)属性定义元素周围的空间。-->
    <div style="margin:auto">
        <!--python自带CSRF验证-->
        {% csrf_token %}
        <!--标签主要确定目的地url和发送方法-->
        <form action="/index/" method="post">            
            <p style="color:blue">您已成功登录</p>
            
        </form>
    </div>
</body>
</html>

python_web/login_demo/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--title标签定义标题-->
    <title>登录</title>
</head>
<body>
    <!--div标识图层，将登录块隔离出来，方面集中控制格式，CSS margin(外边距)属性定义元素周围的空间。-->
    <div style="margin:auto">
        <!--h1标签定义标题-->
        <h1>欢迎登录！</h1>
        <!--标签主要确定目的地url和发送方法-->
        <form action="/" method="post">
            <!--python自带CSRF验证-->
            {% csrf_token %}
            <!--显示提示信息，与return render(request, 'register.html', {'message': message})中message相应-->
            {% if message %}
                <p style="color:red"> {{ message }} </p>
            {% endif %}

            <!--p标签将各个输入框分行-->
            <p>
                <!--label标签为每个输入框提供一个前导提示-->
                <label for="username_desc">用户名：</label>
                <!--input生成一个用户输入框，placeholder属性为输入框提供占位符，
                    autofocus属性为用户名输入框自动聚焦，
                    required表示该输入框必须填写, 与view中request.POST.get('username')对应-->
                <input type="text" id="username" name="username" placeholder="用户名" autofocus required />
            </p>
            <p>
                <!--passowrd类的input标签不会显示明文密码-->
                <label for="id_password">密码：</label>
                <!--与view中request.POST.get('password')对应-->
                <input type="password" id="passowrd" placeholder="密码" name="password" required >
            </p>
            <input type="submit" value="登录">
            <!--新用户注册，可以通过超级链接跳转至注册用户-->
            <a href="/register/" ><ins>注册</ins></a>
        </form>
    </div>
</body>
</html>

python_web/login_demo/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--title标签定义标题-->
    <title>注册为新用户吧</title>
</head>
<body>
    <!--div标识图层，将登录块隔离出来，方面集中控制格式，CSS margin(外边距)属性定义元素周围的空间。-->
    <div style="margin:auto">
        <!--标签主要确定目的地url和发送方法-->
        <form action="/register/" method="post">
            <!--python自带CSRF验证-->
            {% csrf_token %}
            <!--显示提示信息，与return render(request, 'register.html', {'message': message})中message相应-->
            {% if message %}
                <p style="color:red"> {{ message }} </p>
            {% endif %}

            <!--p标签将各个输入框分行-->
            <p>
                <!--label标签为每个输入框提供一个前导提示-->
                <label for="id_username">用户名：</label>
                <!--input生成一个用户输入框，placeholder属性为输入框提供占位符，
                    autofocus属性为用户名输入框自动聚焦，
                    required表示该输入框必须填写, 与view中request.POST.get('username')对应-->
                <input type="text" id="username" name="username" placeholder="用户名" autofocus required />
            </p>
            <p>
                <!--passowrd类的input标签不会显示明文密码-->
                <label for="password1">密 码：</label>
                <!--与view中request.POST.get('password1')对应-->
                <input type="password" id="passowrd1" placeholder="密码" name="password1" required >
            </p>
            <p>
                <!--passowrd类的input标签不会显示明文密码-->
                <label for="password2">密码验证：</label>
                <!--与view中request.POST.get('password2')对应-->
                <input type="password" id="passowrd2" placeholder="密码" name="password2" required >
            </p>
            <p>
                <!--label标签为每个输入框提供一个前导提示-->
                <label for="id_gender">性  别：</label>
                <!--input生成一个用户输入框，placeholder属性为输入框提供占位符与view中request.POST.get('gender')对应-->
                <input type="text" id="gender" name="gender" placeholder="性别"/>
            </p>
            <p>
                <!--label标签为每个输入框提供一个前导提示-->
                <label for="id_mobile">手机号码：</label>
                <!--input生成一个用户输入框，placeholder属性为输入框提供占位符与request.POST.get('mobile')对应-->
                <input type="text" id="mobile" name="mobile" placeholder="手机号码"/>
            </p>
            <input type="submit" value="注册">      
            <a href="/"  ><ins>直接登录</ins></a>    
        </form>
    </div>
</body>
</html>